TRUNCATE TABLE signatures RESTART IDENTITY CASCADE;
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Andri Már', '1000001000', 'x', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Andri Þór', '1000001001', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Anna Guðrún', '0100100002', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Anna Kristín', '1001000003', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Anna Lilja', '0000010004', 'Nunc lorem augue, dignissim at mauris ut, viverra sollicitudin purus. Suspendisse pretium, magna in tristique tincidunt, leo magna vehicula est', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Anna Margrét', '0001000005', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Anna María', '0000010006', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Anna Sigríður', '0010000007', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Arnar Freyr ', '0001000008', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Arnar Már', '0000001009', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Arnar Þór', '0000001010', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Árni Þór', '0000000111', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Bjarki Þór', '0000010012', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Bjarni Þór', '0000010013', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Einar Örn', '0000001014', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Einar Þór', '0000001015', 'sammála', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Eva María', '0000001016', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Guðmundur Ingi', '0100000017', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Guðrún Helga', '0001000018', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Guðrún Jóna', '0000100019', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Guðrún Margrét', '0100000020', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Guðrún María', '0001000021', 'frábært', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Guðrún Ósk', '0000010022', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Guðrún Sigríður', '1000000023', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Gunnar Örn', '0000010024', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Gunnar Þór', '0000010025', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Helga Guðrún', '0001000026', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Helga Kristín', '0010000027', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Helga María', '0000100028', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Íris Ósk', '0000000129', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Jón Gunnar', '0000010030', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Jón Ingi', '0000000131', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Jón Þór', '0000000012', '', true);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Kristín Helga', '0010000033', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Kristín María', '0010000034', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Linda Björk', '0000100035', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel elementum erat. Pellentesque accumsan ex et porttitor ultricies. Praesent pretium velit elit, sed viverra augue auctor at. Phasellus ac vestibulum est. Nunc orci lectus, tincidunt sed ex et, commodo ornare quam. Quisque sodales erat non erat iaculis pulvinar. Sed pulvinar commodo lacus, a iaculis sem pharetra ac.', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Magnús Þór', '0000010036', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Ólafur Þór', '0000010037', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Sindri Snær', '0000100038', '', false);
INSERT INTO signatures (name, nationalId, comment, anonymous) VALUES ('Stefán Þór', '0000010039', '', false);
